import assert from 'node:assert/strict';
const origin='http://127.0.0.1:4183';
const get=path=>fetch(origin+path);
const post=(path,trusted=true)=>fetch(origin+path,{method:'POST',headers:trusted?{Origin:origin}:{Origin:'https://untrusted.example'}});
let n=0;const check=(a,b)=>{assert.equal(a,b);n++};
check((await get('/__shift/capabilities')).status,200);
check((await post('/__shift/reset?run=test12345&scenario=retired',false)).status,403);
check((await post('/__shift/reset?run=x&scenario=retired')).status,403);
check((await post('/__shift/reset?run=test12345&scenario=unknown')).status,400);
check((await post('/__shift/reset?run=test12345&scenario=retired')).status,200);
check((await post('/__shift/renew?run=test12345')).status,409);
check((await get('/fixture/?run=test12345')).status,200);
check((await (await get('/fixture/?run=test12345')).text()).includes('data-version="v1"'),true);
const old=await get('/fixture/v1/checkout.js?run=test12345');check(old.status,200);check(old.headers.get('cache-control'),'public, max-age=31536000, immutable');
check((await post('/__shift/deploy?run=test12345')).status,200);
check((await get('/fixture/v1/checkout.js?run=test12345')).status,410);
check((await (await get('/fixture/?run=test12345')).text()).includes('data-version="v2"'),true);
check((await get('/fixture/v2/checkout.js?run=test12345')).status,200);
check((await post('/__shift/end?run=test12345')).status,200);
check((await get('/fixture/v2/checkout.js?run=test12345')).status,404);
check((await post('/__shift/reset?run=test67890&scenario=expired')).status,200);
check((await get('/fixture/session?run=test67890')).status,200);
check((await post('/__shift/deploy?run=test67890')).status,200);
check((await get('/fixture/session?run=test67890')).status,401);
check((await post('/__shift/renew?run=test67890')).status,200);
check((await get('/fixture/session?run=test67890')).status,200);
check((await post('/__shift/end?run=test67890')).status,200);
check((await get('/api/proxy?url=https://example.com')).status,404);
check((await get('/Cargo.toml')).status,404);
check((await get('/fixtures/retired-v1/checkout.js')).status,404);
check((await get('/assets/shift_core.wasm')).headers.get('content-type'),'application/wasm');
check((await get('/')).headers.get('content-security-policy').includes("default-src 'self'"),true);
for(let i=0;i<8;i++)check((await post(`/__shift/reset?run=limit000${i}&scenario=retained`)).status,200);
check((await post('/__shift/reset?run=limit0009&scenario=retained')).status,429);
for(let i=0;i<8;i++)check((await post(`/__shift/end?run=limit000${i}`)).status,200);
console.log(`Rust localhost HTTP controller: ${n} assertions passed.`);
